version: '3.0'
services:
  mongo:
    image: mongo:3.4.10
    volumes:
      - mongodb:/data/db
  blog:
    image: carlware/blog:devel
    build:
      context: ../backend
      dockerfile: Dockerfile
      # dockerfile: dockerfile.dev
    ports:
      - "50052:50052"
    # command: ['sleep', '10000000000']
    command: ['server']
    volumes:
      - ../backend:/devel
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - PORT=50052
  envoy:
    image: envoyproxy/envoy:latest
    ports:
      - "8080:8080"
      - "9901:9901"
    command: ['envoy', '-c', '/app/envoy/envoy.yaml']
    volumes:
      - ../envoy:/app/envoy
  react:
    image: carlware/react:devel
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"

volumes:
  mongodb:
